@startuml
left to right direction
actor "Администратор" as admin
actor "Пользователь - ученик" as user
rectangle "Веб-приложение для проведения тестирования "{
    usecase "Создание группы обучения" as createGroup
    usecase "Создание нового теста" as createNewTest
    usecase "Редактирование теста" as editTest
    usecase "Создание пользователей" as createNewUser
    usecase "Просмотр результатов тестирования" as viewTestResult
    usecase "Генерация отчётов по результатам тестирования" as reportTest
    usecase "Участие в тестировании" as partTest
    usecase "Просмотр  результатов тестирования пользователем" as resultTest

}

admin --> createGroup
admin --> createNewTest
admin --> editTest
admin --> createNewUser
admin --> viewTestResult
admin --> reportTest


user --> partTest
user --> resultTest

@enduml



@startuml
start
:Открыть веб-приложение;
:Войти под именем администратора;
:Выбор пункта меню Добавить группу обучения;
:Создание группы обучения;
stop
@enduml


@startuml
start
:Открыть веб-приложение;
:Войти под именем администратора;
:Выбор пункта меню Создать тест;
:Создание нового теста;
stop
@enduml


@startuml
start
:Открыть веб-приложение;
:Войти под именем администратора;
:Выбор пункта меню Группы обучения;
:Выбор необходимой группы;
:Выбор теста, выбрать Просмотреть тест;
:Редактирование теста;
stop
@enduml


@startuml
start
:Открыть веб-приложение;
:Войти под именем администратора;
:Выбор пункта меню Создать пользователя;
:Создание пользователей;
stop
@enduml


@startuml
start
:Открыть веб-приложение;
:Войти под именем администратора;
:Выбор пункта меню Результат;
:Просмотр результатов тестирования;
stop
@enduml


@startuml
start
:Открыть веб-приложение;
:Войти под именем администратора;
:Выбор пункта меню Результат;
:Выбор начальной и конечной дат для отчёта;
:Генерация отчётов по результатам тестирования;
stop
@enduml


@startuml
start
:Открыть веб-приложение;
:Войти под именем пользователя;
:Выбор доступного для прохождения теста;
:Участие в тестировании;
stop
@enduml


@startuml
start
:Открыть веб-приложение;
:Войти под именем пользователя;
:Выбор доступного для прохождения теста;
:Участие в тестировании;
:Просмотр  результатов тестирования пользователем;
stop
@enduml